spring:
  application:
    name: api
  docker:
    compose:
      file: compose.dev.yaml
      lifecycle-management: start-and-keep-alive

jwt:
  private:
    key: ${JWT_PRIVATE_KEY:file:certs/app.key}
  public:
    key: ${JWT_PUBLIC_KEY:file:certs/app.pub}